(ns backend.views
    (:use backend.template.main
          [hiccup core page]))

(defn index-page []
      (render-in-template 
          [:div
          [:p "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut erat aliquam, tincidunt erat at, tincidunt enim. Etiam orci diam, viverra eget pretium fringilla, dapibus tempus lectus. In volutpat mauris eros, eu luctus libero hendrerit et. Morbi consectetur feugiat augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus gravida, lorem non porta sollicitudin, nisl leo posuere tellus, quis tincidunt purus velit eget arcu. Quisque lobortis velit at mauris luctus laoreet. Cras venenatis id eros vitae rhoncus. Praesent porttitor eros tristique sem porta, vel pellentesque quam commodo. Etiam cursus ligula at enim sollicitudin dapibus. Curabitur eu rhoncus sapien, nec commodo urna. Cras aliquam lectus sed lacus pretium volutpat."]
          [:p "sapien turpis, laoreet sit amet mauris sit amet, mollis laoreet ante. Ut ut lacus lectus. Pellentesque nec felis at nibh sodales lacinia. Vivamus at nisi sit amet neque ultricies consectetur nec porttitor nisl. Aenean ut tellus et dolor sodales faucibus id non quam. Nunc et libero et ipsum pellentesque aliquam in et mi. Sed eu augue nunc. Maecenas tincidunt viverra fringilla. Quisque ac diam sem. Aenean cursus, purus id malesuada semper, magna elit faucibus magna, ac tristique dui ligula dapibus purus. Sed in varius metus. Nam nec dui quam. Mauris egestas lectus vitae fermentum fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse potenti."]
          [:p "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut a interdum est, ac porta purus. Integer fringilla metus eu accumsan commodo. Curabitur varius aliquet nisl nec imperdiet. Etiam vehicula quam quam, eu ultrices neque lobortis sed. Nunc iaculis ullamcorper porta. Maecenas porta odio ac fringilla euismod. Morbi sit amet nunc dignissim, lacinia nulla in, vehicula eros. Nam turpis leo, posuere et posuere non, rutrum non tellus. Duis eget erat orci. Pellentesque ut pharetra orci, vitae gravida dolor. Suspendisse bibendum malesuada lorem. Nam convallis, tortor vitae vehicula tempor, nulla dolor gravida erat, vitae ultrices arcu mauris vitae tellus. Donec scelerisque, orci sed dictum facilisis, turpis risus commodo nibh, at bibendum eros massa sed lorem."]
          [:p "fermentum quis justo sit amet consequat. Suspendisse venenatis tellus eget libero dictum, eu congue nisl imperdiet. Pellentesque egestas et odio in rhoncus. Mauris porta sodales tellus, a viverra risus tristique at. Pellentesque vestibulum in massa ut facilisis. Vestibulum sit amet augue eu eros luctus convallis. Nulla egestas eleifend purus, id convallis purus. Quisque lacinia felis at feugiat sollicitudin."]]))
